services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sim
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  cpp:
    build:
      context: ./simulation
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

